language: node_js
node_js:
  - '4'

env:
  global:
    - ENCRYPTION_LABEL: "d7ffc1eaa225"
    - COMMIT_AUTHOR_EMAIL: "patternfly-build@redhat.com"
    - TRIGGER_REPO_SLUG: "patternfly-webcomponents/patternfly-webcomponents"
    - TRIGGER_REPO_BRANCH: "master"

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - npm install patternfly-eng-release

install: true

script:
  - npm run build-travis

after_success:
  - npm run publish-travis
